version: '3'
services:
  app:
    container_name: nestjs_boilerplate
    restart: always
    build: .
    ports:
      - '${PORT}:80'
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: 'UTC'
      PGTZ: 'UTC'
    ports:
      - '5432:5432'
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
